name: Update Activity Log

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # 每6小時自動更新

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate activity
        uses: Readme-Workflows/recent-activity@main
        with:
          CONFIG_FILE: .github/recent-activity.config.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update activity log"
